name: Run all tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        mcu: ["t214", "t414", "t814"]

    steps:
    - uses: actions/checkout@v4

    - name: Install asxxxx
      run: |
        wget --no-verbose --content-disposition https://github.com/6502org/6502.org/raw/74f5d0c0f9b73d5e353bde7b3b25ea7f43b527a1/public/tools/asm/asxs5p50.zip
        unzip -q asxs5p50.zip
        make -C asxv5pxx/asxmak/linux/build all
        echo "$PWD/asxv5pxx/asxmak/linux/build" >> $GITHUB_PATH

    - name: Build the firmware (${{ matrix.mcu }} version)
      run: |
        make -C firmware MCU=${{ matrix.mcu }}
        cat firmware/mxlock_${{ matrix.mcu }}_flash.lst
        cat firmware/mxlock_${{ matrix.mcu }}_fuses.lst
        cat firmware/mxlock_${{ matrix.mcu }}_eeprom.lst

    - name: 'Upload build artifacts'
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts-${{ matrix.mcu }}
        path: |
            firmware/mxlock_${{ matrix.mcu }}_flash.*
            firmware/mxlock_${{ matrix.mcu }}_fuses.*
            firmware/mxlock_${{ matrix.mcu }}_eeprom.*
